/*
 * This source file was generated by the Gradle 'init' task
 */
package org.graceliying;

import lombok.extern.slf4j.Slf4j;
import org.graceliying.snippets.LambdaExamples;

@Slf4j
public class App {

    public static void main(String[] args) {
        log.info("Running Java Code Snippets");

        Runnable lambdaExamples = new LambdaExamples();
        lambdaExamples.run();
    }
}
